workflows:
  ios-workflow:
    name: Build iOS App
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter packages get
      - name: Build iOS App
        script: |
          flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa